### ISSUE TITLE
Run Inspec from Ansible

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/configs-homelab#71]
- [ ] Introduce dedicated test playbook
- [ ] Run Inspec against my linux machines (the respective host)
    - [ ] Inspec runs from a docker container
- [ ] Test with basic Inspec profile
- [ ] #70
    - [ ] Roll out to all repos

### Suggestion from Google Gemini:
```yaml
---
- name: Run InSpec tests in a Docker container
  hosts: your_target_machines
  become: true  # If Docker commands require sudo

  vars:
    inspec_image: chef/inspec
    inspec_profile: /path/to/your/inspec/profile  # Local profile on the target machine
    inspec_command: exec {{ inspec_profile }} --reporter json

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull InSpec Docker image
      docker_image:
        name: "{{ inspec_image }}"
        state: present

    - name: Run InSpec container
      docker_container:
        name: inspec-test-container
        image: "{{ inspec_image }}"
        volumes:
          - "{{ inspec_profile }}:/inspec-profile:ro" # Mount local profile
          # Add other volume mounts as needed
        command: "{{ inspec_command }}"
        detach: false  # Keep the container running until the command finishes
        rm: true      # Automatically remove the container after it exits
      register: inspec_results

    - name: Display InSpec results
      debug:
        var: inspec_results.stdout

    # Optional: Fail the playbook if InSpec tests fail
    - name: Fail if InSpec tests failed
      fail:
        msg: "InSpec tests failed. See output above."
      when: "'failures' in inspec_results.stdout or 'exception' in inspec_results.stdout"
```
