### ISSUE TITLE
Turn Ansible Playbook "cleanup" into a global task

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/configs-homelab#81]
Upside for ansbible: would clean up every machine

Upside task: more light weight and can be run from anywhere with `dir: {{.PWD}}`

```yaml
  cleanup:
    desc: Cleanup the WSL instance by deleting old / obsolete artifacts and files
    summary: |
      Remove all docker build caches
      Remove stopped containers, unused networks, dangling images and dangling volumes
      Remove {{.PORTAINER_PASSWD_FILE}}
    cmds:
      - docker buildx prune --all -f
      - docker system prune --all -f --volumes
      - docker volume prune -f
      - docker volume ls -q | xargs docker volume rm
      - rm -f {{.PORTAINER_PASSWD_FILE}}
```

- [x] Remove all `System Volume Information` as well (recursively from root?)
