### ISSUE TITLE
Clone Repositories with Ansible if they do not yet exist on the respective machine

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/configs-homelab#91]
In a dedicated playbook
Create directories as well (r e-use existing task)

```yaml
- name: Block  ----  Clone repositories
  block:

    # This task will loop over each item in your list of repositories.
    # The 'stat' module will check for the presence of the destination directory.
    - name: Config  ----  Get status of {{ item.dest }}/{{ item.name }}
      ansible.builtin.stat:
        path: "{{ item.dest }}/{{ item.name }}"
      register: repo_directory_status
      loop:
        # Pimcore
        - { dest: "{{ repo_dir_cpa_online }}", name: "cpa.dam", url: "{{gitlab }}:cpa.online/cpa.dam.git" }
        # Platform
        - { dest: "{{ repo_dir_platform }}", name: "cluster-helm-charts	", url: "{{gitlab }}:platform/cluster-helm-charts.git" }
        - { dest: "{{ repo_dir_platform }}", name: "dc-2-argocd-autopilot", url: "{{gitlab }}:platform/dc-2-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "dc-argocd-autopilot", url: "{{gitlab }}:platform/dc-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "dummy-smtp-server", url: "{{gitlab }}:platform/dummy-smtp-server.git" }
        - { dest: "{{ repo_dir_platform }}", name: "infra-argocd-autopilot", url: "{{gitlab }}:platform/infra-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k-3-s-argocd-autopilot", url: "{{gitlab }}:platform/k-3-s-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k3s-gabor-argocd-autopilot", url: "{{gitlab }}:platform/k3s-gabor-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k3s-gabor-prod-argocd-autopilot", url: "{{gitlab }}:platform/k3s-gabor-prod-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k-3-s-rieker-argocd-autopilot", url: "{{gitlab }}:platform/k-3-s-rieker-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k3s-rieker-prod-argocd-autopilot", url: "{{gitlab }}:platform/k3s-rieker-prod-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k8s-kopf", url: "{{gitlab }}:platform/k8s-kopf.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k8s-test-tools", url: "{{gitlab }}:platform/k8s-test-tools.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k8s-test-tools-manifests", url: "{{gitlab }}:platform/k8s-test-tools-manifests.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k8s-tools", url: "{{gitlab }}:platform/k8s-tools.git" }
        - { dest: "{{ repo_dir_platform }}", name: "k8s-tools-manifests", url: "{{gitlab }}:platform/k8s-tools-manifests.git" }
        - { dest: "{{ repo_dir_platform }}", name: "kafka-helm-charts", url: "{{gitlab }}:platform/kafka-helm-charts.git" }
        - { dest: "{{ repo_dir_platform }}", name: "prod-argocd-autopilot", url: "{{gitlab }}:platform/prod-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "sf-next-helmcharts", url: "{{gitlab }}:platform/sf-next-helmcharts.git" }
        - { dest: "{{ repo_dir_platform }}", name: "sf-next-load-tests", url: "{{gitlab }}:platform/sf-next-load-tests.git" }
        - { dest: "{{ repo_dir_platform }}", name: "test-argocd-autopilot", url: "{{gitlab }}:platform/test-argocd-autopilot.git" }
        - { dest: "{{ repo_dir_platform }}", name: "test-argocd-secrets", url: "{{gitlab }}:platform/test-argocd-secrets.git" }
        # SF.Next Backend
        - { dest: "{{ repo_dir_sf_next_backend }}", name: "sf2-build-scripts", url: "{{ gitlab }}:sf-next/sf.next-backend/sf2-build-scripts.git" }
        # Sommerfeld
        - { dest: "{{ repo_dir_sommerfeld }}", name: "configs", url: "{{ gitlab }}:sommerfeld/configs.git" }
      loop_control:
        label: "Check {{ item.dest }}/{{ item.name }} for repo {{ item.url }}"

    # This task loops over the *results* of the previous stat task.
    # 'item' here refers to an individual result dictionary from 'repo_directory_status.results'.
    - name: Config  ----  Clone {{ item-item.url }} if not existing
      ansible.builtin.git:
        repo: "{{ item.item.url }}"
        dest: "{{ item.item.dest }}/{{ item.item.name }}"
        clone: true
        update: false
        key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"
        accept_hostkey: true
      when: not item.stat.exists
      loop: "{{ repo_directory_status.results }}"
      loop_control:
        label: "Clone: {{ item.item.url }} into {{ item.item.dest }}/{{ item.item.name }}"
```
